// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05.EF___Advanced_Quering;

#nullable disable

namespace _05.EF___Advanced_Quering.Migrations
{
    [DbContext(typeof(BookShopContext))]
    partial class BookShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShop.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("69486502-9aee-40e2-a1c6-191bcf18fcd3"),
                            FirstName = "Jakayla",
                            LastName = "Bergstrom"
                        },
                        new
                        {
                            AuthorId = new Guid("84cd49e2-219d-46b4-9369-5e21c7aaaef1"),
                            FirstName = "Jack",
                            LastName = "Quigley"
                        },
                        new
                        {
                            AuthorId = new Guid("5f0a7a2d-64a6-4a15-94d0-e56eab85b15d"),
                            FirstName = "Suzanne",
                            LastName = "Halvorson"
                        },
                        new
                        {
                            AuthorId = new Guid("1bf56aab-9c8e-436d-84e2-35c17f96adbe"),
                            FirstName = "Jazmin",
                            LastName = "Satterfield"
                        },
                        new
                        {
                            AuthorId = new Guid("90847da7-59ed-4645-a440-a3795df3a1cf"),
                            FirstName = "Ignatius",
                            LastName = "Grant"
                        },
                        new
                        {
                            AuthorId = new Guid("9424871e-e103-4727-a381-144525ca2b5a"),
                            FirstName = "Anthony",
                            LastName = "Davis"
                        },
                        new
                        {
                            AuthorId = new Guid("1bfc89c9-0119-418b-b8f0-c4977582fc7d"),
                            FirstName = "Taryn",
                            LastName = "Gulgowski"
                        },
                        new
                        {
                            AuthorId = new Guid("5a11bd36-f79b-4b81-b996-4309a0634305"),
                            FirstName = "Dallas",
                            LastName = "Grant"
                        },
                        new
                        {
                            AuthorId = new Guid("574bcdb1-063b-4731-bfc8-51fe2f80cc7f"),
                            FirstName = "Marcos",
                            LastName = "Emard"
                        },
                        new
                        {
                            AuthorId = new Guid("6320f78b-a0c9-4c1e-844b-0c1a495016b3"),
                            FirstName = "Keyshawn",
                            LastName = "Kilback"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgeRestriction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Copies")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("60e9c698-9e78-470f-a03e-5e41c5d65625"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("574bcdb1-063b-4731-bfc8-51fe2f80cc7f"),
                            Copies = 854,
                            Description = "Impedit officiis quia deleniti. Non delectus fuga. Ut illo labore ut laborum nam aut. At doloribus natus necessitatibus voluptatem ipsa aut iusto iure. Nostrum rerum nostrum ut.",
                            EditionType = "Promo",
                            Price = 39.1068610539912487m,
                            ReleaseDate = new DateTime(2015, 6, 7, 3, 25, 6, 117, DateTimeKind.Local).AddTicks(4560),
                            Title = "et"
                        },
                        new
                        {
                            BookId = new Guid("43d1ee8c-e71d-48b4-bef7-7d6c2ed2d0e7"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("5f0a7a2d-64a6-4a15-94d0-e56eab85b15d"),
                            Copies = 597,
                            Description = "Repellat molestiae voluptatem. Vitae autem animi possimus aliquid sed. Maxime aliquam quia aspernatur delectus.",
                            EditionType = "Gold",
                            Price = 861.637086633975805m,
                            ReleaseDate = new DateTime(2018, 5, 27, 6, 14, 56, 414, DateTimeKind.Local).AddTicks(1136),
                            Title = "asperiores"
                        },
                        new
                        {
                            BookId = new Guid("6cb2809e-5134-4b97-89e4-0eb7f8509bae"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("6320f78b-a0c9-4c1e-844b-0c1a495016b3"),
                            Copies = 223,
                            Description = "Ea quod ea. Molestias recusandae sed a ipsa odit maxime illum. Doloremque ut omnis ad inventore nesciunt qui sapiente veritatis.",
                            EditionType = "Normal",
                            Price = 815.053236594884416m,
                            ReleaseDate = new DateTime(2008, 9, 23, 18, 35, 20, 210, DateTimeKind.Local).AddTicks(558),
                            Title = "fuga"
                        },
                        new
                        {
                            BookId = new Guid("ac0fe20b-adee-46ec-b57d-10c9efdd81f8"),
                            AgeRestriction = "Minor",
                            AuthorId = new Guid("5a11bd36-f79b-4b81-b996-4309a0634305"),
                            Copies = 972,
                            Description = "Sed est nihil est. Rerum velit aspernatur optio veritatis porro veniam porro. Amet et illo fuga.",
                            EditionType = "Normal",
                            Price = 863.488115600206726m,
                            ReleaseDate = new DateTime(2013, 4, 22, 18, 52, 14, 194, DateTimeKind.Local).AddTicks(5440),
                            Title = "et"
                        },
                        new
                        {
                            BookId = new Guid("eff61165-5ba3-4a7b-b9a2-cae2a96de3eb"),
                            AgeRestriction = "Minor",
                            AuthorId = new Guid("6320f78b-a0c9-4c1e-844b-0c1a495016b3"),
                            Copies = 916,
                            Description = "Qui officia reiciendis fugit. Excepturi harum possimus pariatur harum veniam sint quam sint nam. Voluptates reiciendis qui sit amet sunt quis ad sunt.",
                            EditionType = "Normal",
                            Price = 666.179217504366067m,
                            ReleaseDate = new DateTime(2008, 12, 6, 19, 15, 22, 468, DateTimeKind.Local).AddTicks(5059),
                            Title = "sed"
                        },
                        new
                        {
                            BookId = new Guid("2af78f69-474b-48ee-bfcd-9a059402f97c"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("574bcdb1-063b-4731-bfc8-51fe2f80cc7f"),
                            Copies = 613,
                            Description = "Perferendis blanditiis quo ipsa voluptates eum dolor sequi. Ut omnis libero qui non. Nemo quasi quia id voluptates. Consequatur quidem veniam repellat vel omnis. Aperiam qui provident consequatur rem molestiae in.",
                            EditionType = "Promo",
                            Price = 998.072641505949832m,
                            ReleaseDate = new DateTime(2018, 8, 24, 22, 34, 52, 670, DateTimeKind.Local).AddTicks(8169),
                            Title = "numquam"
                        },
                        new
                        {
                            BookId = new Guid("03d0c700-3531-4ccd-95a7-0ff72a5a7714"),
                            AgeRestriction = "Minor",
                            AuthorId = new Guid("5a11bd36-f79b-4b81-b996-4309a0634305"),
                            Copies = 665,
                            Description = "Sint vel reprehenderit. Eos distinctio et doloremque qui velit necessitatibus sed corporis hic. Minus tenetur et eligendi. Necessitatibus sit sit non minus nihil quia dolores aspernatur nobis. Et alias ullam rerum dolorem est atque. Reiciendis excepturi quod fuga similique laborum nihil omnis tempora qui.",
                            EditionType = "Normal",
                            Price = 629.305273226878687m,
                            ReleaseDate = new DateTime(2020, 12, 11, 14, 29, 4, 490, DateTimeKind.Local).AddTicks(2627),
                            Title = "sit"
                        },
                        new
                        {
                            BookId = new Guid("98b6b3d1-b33a-4f01-aa97-4d0544429329"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("6320f78b-a0c9-4c1e-844b-0c1a495016b3"),
                            Copies = 449,
                            Description = "Consequuntur in cumque occaecati ab dolor velit repudiandae. Vero ullam ipsa quod dicta. Earum et et nesciunt reprehenderit eius ipsa. Reprehenderit occaecati cum reprehenderit. Itaque a dolores ratione vitae beatae labore. Illo iste dignissimos veritatis quae error.",
                            EditionType = "Gold",
                            Price = 978.164478027357994m,
                            ReleaseDate = new DateTime(2011, 2, 23, 4, 30, 28, 89, DateTimeKind.Local).AddTicks(2182),
                            Title = "tempore"
                        },
                        new
                        {
                            BookId = new Guid("6cc7242a-4a69-4de9-8501-7b99bfaa053a"),
                            AgeRestriction = "Adult",
                            AuthorId = new Guid("84cd49e2-219d-46b4-9369-5e21c7aaaef1"),
                            Copies = 193,
                            Description = "Incidunt beatae molestiae ut qui maiores laborum iusto incidunt. Unde quis reiciendis voluptatem ea. Minus voluptas est temporibus culpa tempore praesentium possimus praesentium. Dolorem eum harum saepe excepturi nobis perferendis.",
                            EditionType = "Promo",
                            Price = 672.068155881059164m,
                            ReleaseDate = new DateTime(2012, 7, 25, 5, 46, 29, 274, DateTimeKind.Local).AddTicks(8723),
                            Title = "ut"
                        },
                        new
                        {
                            BookId = new Guid("b50e0c6b-2b30-4f1e-bbaf-da545471b49f"),
                            AgeRestriction = "Teen",
                            AuthorId = new Guid("1bfc89c9-0119-418b-b8f0-c4977582fc7d"),
                            Copies = 226,
                            Description = "Quia labore quis ipsam occaecati praesentium repudiandae reprehenderit ipsum. Doloribus similique tempore nemo non eligendi sint assumenda perspiciatis. Sint ipsam delectus aut id cumque excepturi. Omnis non deleniti qui ipsam consequuntur mollitia. Neque iste dolores illo quia.",
                            EditionType = "Gold",
                            Price = 625.843149533216632m,
                            ReleaseDate = new DateTime(2016, 11, 28, 11, 26, 15, 217, DateTimeKind.Local).AddTicks(5136),
                            Title = "harum"
                        });
                });

            modelBuilder.Entity("BookShop.Models.BookCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("24a4ce83-37a7-4dd0-81b9-4ec14fb6dd61"),
                            BookId = new Guid("eff61165-5ba3-4a7b-b9a2-cae2a96de3eb")
                        },
                        new
                        {
                            CategoryId = new Guid("3a1d58e2-53cd-49c0-a91a-aef760eacb9f"),
                            BookId = new Guid("2af78f69-474b-48ee-bfcd-9a059402f97c")
                        },
                        new
                        {
                            CategoryId = new Guid("3a1d58e2-53cd-49c0-a91a-aef760eacb9f"),
                            BookId = new Guid("ac0fe20b-adee-46ec-b57d-10c9efdd81f8")
                        },
                        new
                        {
                            CategoryId = new Guid("94566ec9-f6ac-4ca1-bbc7-69d92416ff06"),
                            BookId = new Guid("43d1ee8c-e71d-48b4-bef7-7d6c2ed2d0e7")
                        },
                        new
                        {
                            CategoryId = new Guid("94566ec9-f6ac-4ca1-bbc7-69d92416ff06"),
                            BookId = new Guid("2af78f69-474b-48ee-bfcd-9a059402f97c")
                        });
                });

            modelBuilder.Entity("BookShop.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("3a1d58e2-53cd-49c0-a91a-aef760eacb9f"),
                            Name = "Computers, Automotive & Outdoors"
                        },
                        new
                        {
                            CategoryId = new Guid("401c8ca8-e9b6-4712-839e-68c83516438f"),
                            Name = "Books, Kids & Toys"
                        },
                        new
                        {
                            CategoryId = new Guid("dcf58143-618c-46f0-b302-51fd94388aab"),
                            Name = "Electronics, Health & Games"
                        },
                        new
                        {
                            CategoryId = new Guid("797cbd01-2db7-4d17-9492-9fc61b837844"),
                            Name = "Health"
                        },
                        new
                        {
                            CategoryId = new Guid("46b8c0da-be8b-4906-8bc3-4b0ee49f9388"),
                            Name = "Kids & Grocery"
                        },
                        new
                        {
                            CategoryId = new Guid("24a4ce83-37a7-4dd0-81b9-4ec14fb6dd61"),
                            Name = "Garden"
                        },
                        new
                        {
                            CategoryId = new Guid("11f00845-9aad-4958-a80e-412f81411e90"),
                            Name = "Toys & Music"
                        },
                        new
                        {
                            CategoryId = new Guid("d45fbe55-736e-4a9c-840d-9c5909995dee"),
                            Name = "Movies & Music"
                        },
                        new
                        {
                            CategoryId = new Guid("94566ec9-f6ac-4ca1-bbc7-69d92416ff06"),
                            Name = "Outdoors & Books"
                        },
                        new
                        {
                            CategoryId = new Guid("59b911be-01b8-4ce2-b437-92d3f5ad2360"),
                            Name = "Sports, Outdoors & Grocery"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.HasOne("BookShop.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShop.Models.BookCategory", b =>
                {
                    b.HasOne("BookShop.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookShop.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookShop.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookShop.Models.Book", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("BookShop.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
